db = new Mongo("localhost:27017").getDB("test");

db.createCollection("roles");

db.getCollection("roles").insertMany([
  {
    _id: ObjectId("62b5f0290250004d53f8c586"),
    type: "Staff",
    name: "staff",
    createdAt: ISODate("2022-06-24T17:11:05.527Z"),
    permissions: {
      category: {
        "create:any": true,
        "update:any": true,
        "delete:any": true,
        "read:any": true,
        "create:own": true,
        "read:own": true,
        "update:own": true,
        "delete:own": true,
      },
      admin: {
        "create:any": false,
        "update:any": false,
        "delete:any": false,
        "read:any": true,
        "create:own": false,
        "read:own": true,
        "update:own": false,
        "delete:own": false,
      },
      user: {
        "create:any": false,
        "update:any": false,
        "delete:any": false,
        "read:any": true,
        "create:own": true,
        "read:own": true,
        "update:own": true,
        "delete:own": true,
      },
      data: {
        "create:any": true,
        "update:any": true,
        "delete:any": true,
        "read:any": true,
        "create:own": true,
        "read:own": true,
        "update:own": true,
        "delete:own": true,
      },
      role: {
        "create:any": false,
        "update:any": false,
        "delete:any": false,
        "read:any": true,
        "create:own": false,
        "read:own": true,
        "update:own": false,
        "delete:own": true,
      },
      staff: {
        "create:any": false,
        "update:any": false,
        "delete:any": false,
        "read:any": true,
        "create:own": true,
        "read:own": true,
        "update:own": true,
        "delete:own": true,
      },
    },
    __v: 0,
  },
  {
    _id: ObjectId("62b5f0290250004d53f8c583"),
    type: "Admin",
    name: "admin",
    createdAt: ISODate("2022-06-24T17:11:05.527Z"),
    permissions: {
      category: {
        "create:any": true,
        "update:any": true,
        "delete:any": true,
        "read:any": true,
        "create:own": true,
        "read:own": true,
        "update:own": true,
        "delete:own": true,
      },
      admin: {
        "create:any": true,
        "update:any": true,
        "delete:any": true,
        "read:any": true,
        "create:own": true,
        "read:own": true,
        "update:own": true,
        "delete:own": true,
      },
      user: {
        "create:any": true,
        "update:any": true,
        "delete:any": true,
        "read:any": true,
        "create:own": true,
        "read:own": true,
        "update:own": true,
        "delete:own": true,
      },
      data: {
        "create:any": true,
        "update:any": true,
        "delete:any": true,
        "read:any": true,
        "create:own": true,
        "read:own": true,
        "update:own": true,
        "delete:own": true,
      },
      role: {
        "create:any": true,
        "update:any": true,
        "delete:any": true,
        "read:any": true,
        "create:own": true,
        "read:own": true,
        "update:own": true,
        "delete:own": true,
      },
      staff: {
        "create:any": true,
        "update:any": true,
        "delete:any": true,
        "read:any": true,
        "create:own": true,
        "read:own": true,
        "update:own": true,
        "delete:own": true,
      },
    },
    __v: 0,
  },
]);
